# --- Script generated by matflow-defdap version 0.1.0 at .. on .......
# ---   ...

import sys
import json

def main(arg1, arg2, arg3):
    
    EbsdMap = load_EBSD_map()
    DicMap = load_DIC_map()
    link_EBSD_DIC_map(EbsdMap, DicMap)
    DIC_image = get_DIC_image(DicMap)
    
    return {
        'DIC_image': DIC_image,
    }

def load_EBSD_map(args):
    pass

def load_DIC_map(args):
    pass

def link_EBSD_DIC_map(args):
    pass

def get_DIC_image(args):
    pass

if __name__ == '__main__':
    
    with Path(sys.argv[1]).open('r') as handle: 
        inputs = json.load(handle)
    
    outputs = main(**inputs)
    
    with Path('outputs.json').open('w') as handle:
        json.dump(outputs, handle)
    